language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libsdl2-dev
before_script:
  - cd ../
  - git clone --branch 1.1.0 https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-sdl/.travis_build_config.rb build_config.rb
script:
  - rake all test
